=== politecnico2022-2/Ejercicio1TallerXML/listaVentas.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ListaVentas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="venta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="importe" type="xs:string"/>
                            <xs:element name="comprador" type="xs:string"/>
                            <xs:element name="vendedor" type="xs:string"/>
                            <xs:element name="fecha" type="xs:string" minOccurs="0"/>
                            <xs:element name="CodFactura" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== politecnico2022-2/Ejercicio1TallerXML/listaVentasXSD.xml
<?xml version="1.0" encoding="UTF-8" ?>

<ListaVentas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="listaVentas.xsd">
    <venta>
        <importe>Tela fina</importe>
        <comprador>Cristian</comprador>
        <vendedor>Lucas Restrepo</vendedor>
        <fecha>2022-10-09</fecha>
        <CodFactura>100DC63599315</CodFactura>
    </venta>

    <venta>
        <importe>Gaseous de MX</importe>
        <comprador>Josefina</comprador>
        <vendedor>Karol</vendedor>
        <CodFactura>D159566C965E</CodFactura>
    </venta>
</ListaVentas>
